[pr_reviewer]
persistent_comment=true
[pr_custom_prompt]
prompt = """
Analyze the changes in the pull request automatically using AI, and output a comment that not only provides a general review but also highlights edge cases in an interesting and engaging way.
"""
[config]
response_language="ja-JP"